<script lang="ts">
 import { page } from '$app/state'; import { onMount } from 'svelte'; import PageHeader from '$lib/components/PageHeader.svelte'; import { listTasks } from '$lib/api/tasks'; import { listMilestones } from '$lib/api/milestones'; import type { Milestone, TaskView } from '$lib/api/types';
 const projectKey=$derived(String(page.params.projectKey ?? '')); let tasks=$state<TaskView[]>([]), milestones=$state<Milestone[]>([]), loading=$state(true), errorMessage=$state('');
 onMount(async()=>{try{const [t,m]=await Promise.all([listTasks(projectKey,1,100),listMilestones(projectKey)]);tasks=t.data.items;milestones=m.data.items}catch(e){errorMessage=e instanceof Error?e.message:'日历加载失败'}finally{loading=false}});
 const groups=$derived([...new Set(tasks.filter(t=>t.due_at).map(t=>t.due_at!.slice(0,10)))].sort());
</script>
<PageHeader title="日历" eyebrow="Calendar" description="按截止日期查看任务和里程碑，未设置日期的任务单独归类。" />
{#if errorMessage}<div class="workspace-card error-state">{errorMessage}</div>{/if}{#if loading}<section class="workspace-card state-box">正在加载日程…</section>{:else}<div class="calendar-grid">{#each groups as date}<section class="workspace-card day-card"><header><strong>{date}</strong><span>{tasks.filter(t=>t.due_at?.slice(0,10)===date).length} 项</span></header>{#each tasks.filter(t=>t.due_at?.slice(0,10)===date) as task}<a href={`/tasks/${task.task_key}`}><code>{task.task_key}</code><strong>{task.title}</strong></a>{/each}{#each milestones.filter(m=>m.due_date===date) as item}<div class="milestone-item"><span>里程碑</span><strong>{item.name}</strong></div>{/each}</section>{:else}<section class="workspace-card empty-calendar">没有设置截止日期的任务会显示在这里。<div class="unscheduled">{#each tasks.filter(t=>!t.due_at) as task}<a href={`/tasks/${task.task_key}`}><code>{task.task_key}</code>{task.title}</a>{:else}<span>暂无未排期任务</span>{/each}</div></section>{/each}</div>{/if}
<style>.calendar-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.day-card{min-height:180px}.day-card header{display:flex;justify-content:space-between;padding-bottom:12px;border-bottom:1px solid var(--color-border)}.day-card header span{color:var(--color-text-muted);font-size:12px}.day-card a,.milestone-item{display:grid;gap:5px;padding:12px 0;border-bottom:1px solid var(--color-border)}.day-card code,.unscheduled code{font-family:var(--font-mono);font-size:11px;color:var(--color-primary-strong)}.milestone-item span{font-size:11px;color:var(--color-warning)}.empty-calendar{text-align:center;color:var(--color-text-muted)}.unscheduled{display:grid;gap:8px;margin-top:18px;text-align:left}.unscheduled a{display:flex;gap:8px;padding:9px;background:#f7f8fb;border-radius:8px}.error-state{color:var(--color-danger);margin-bottom:16px}.state-box{text-align:center;color:var(--color-text-muted)}</style>
