<script lang="ts">
 import { onMount } from 'svelte'; import PageHeader from '$lib/components/PageHeader.svelte'; import { listDepartments, createDepartment, updateDepartment, deleteDepartment } from '$lib/api/departments'; import { confirmDialog, promptDialog } from '$lib/features/ui/dialog.svelte'; import type { DepartmentView } from '$lib/api/types';
 let departments=$state<DepartmentView[]>([]), loading=$state(true), errorMessage=$state(''), name=$state(''), code=$state(''), parentId=$state(''), saving=$state(false);
 const roots=$derived(departments.filter(d=>!d.parent_id)); const children=(id:string)=>departments.filter(d=>d.parent_id===id);
 onMount(load); async function load(){try{departments=(await listDepartments()).data.items}catch(e){errorMessage=e instanceof Error?e.message:'部门加载失败'}finally{loading=false}}
 async function add(event:SubmitEvent){event.preventDefault();if(!name.trim()||!code.trim())return;saving=true;try{const d=(await createDepartment({name:name.trim(),code:code.trim(),parent_id:parentId||null})).data;departments=[...departments,d];name='';code='';parentId=''}catch(e){errorMessage=e instanceof Error?e.message:'新增部门失败'}finally{saving=false}}
 async function edit(d:DepartmentView){const value=await promptDialog({title:'重命名部门',label:'部门名称',initial:d.name});if(!value?.trim())return;try{const updated=(await updateDepartment(d.id,{name:value.trim()})).data;departments=departments.map(i=>i.id===d.id?updated:i)}catch(e){errorMessage=e instanceof Error?e.message:'修改部门失败'}}
 async function remove(d:DepartmentView){if(!(await confirmDialog({title:'删除部门',message:`确定逻辑删除部门“${d.name}”吗？`,confirmLabel:'删除',danger:true})))return;try{await deleteDepartment(d.id);departments=departments.filter(i=>i.id!==d.id)}catch(e){errorMessage=e instanceof Error?e.message:'删除部门失败'}}
</script>
<PageHeader title="部门" eyebrow="Department" description="用户可以属于多个部门；父部门可以查看其下级部门信息。" />
{#if errorMessage}<div class="workspace-card error-state">{errorMessage}</div>{/if}<section class="workspace-card create-card"><h2>新增部门</h2><form onsubmit={add}><input bind:value={name} placeholder="部门名称" /><input bind:value={code} placeholder="部门编码" /><select bind:value={parentId}><option value="">顶级部门</option>{#each departments as department}<option value={department.id}>{department.name}</option>{/each}</select><button class="primary-button" disabled={saving}>{saving?'保存中…':'创建部门'}</button></form></section>{#if loading}<section class="workspace-card state-box">正在加载部门树…</section>{:else}<section class="workspace-card tree-card"><div class="tree">{#each roots as root}<article><header><a href={`/departments/${root.id}`}><strong>{root.name}</strong><small>{root.code}</small></a><div><button class="text-button" onclick={()=>edit(root)}>编辑</button><button class="text-button danger-text" onclick={()=>remove(root)}>删除</button></div></header>{#each children(root.id) as child}<div class="child"><a href={`/departments/${child.id}`}><strong>{child.name}</strong><small>{child.code}</small></a><span>{children(child.id).length} 个下级</span></div>{/each}</article>{:else}<p class="empty-inline">还没有部门。</p>{/each}</div></section>{/if}
<style>.create-card h2{margin:0 0 14px}.create-card form{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:10px}.tree{display:grid;gap:14px}.tree article{border:1px solid var(--color-border);border-radius:12px;padding:16px}.tree header,.child{display:flex;align-items:center;justify-content:space-between;gap:12px}.tree header a,.child a{display:grid;gap:4px}.tree small,.child small,.child span{color:var(--color-text-muted);font-size:12px}.child{margin-top:10px;padding:10px 12px 10px 28px;border-left:2px solid var(--color-primary-soft);background:#fafbfc}.text-button{border:0;background:transparent;cursor:pointer;font-weight:700;color:var(--color-primary-strong)}.danger-text{color:var(--color-danger)}.error-state{color:var(--color-danger);margin-bottom:16px}.state-box{text-align:center;color:var(--color-text-muted)}@media(max-width:760px){.create-card form{grid-template-columns:1fr}.tree header{align-items:start}.tree header>div{display:grid}}</style>
