<script lang="ts">
  import { page } from '$app/state';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import { listDepartments, listDepartmentGrants, listProjectMembers, addProjectMember, updateProjectMember, revokeProjectMember, grantDepartment, revokeDepartmentGrant } from '$lib/api/projects';
  import type { DepartmentView, ProjectDepartmentGrant, ProjectMember } from '$lib/api/types';
  import { onMount } from 'svelte';
  import { confirmDialog } from '$lib/features/ui/dialog.svelte';
  const projectKey = $derived(String(page.params.projectKey ?? ''));
  let members = $state<ProjectMember[]>([]), grants = $state<ProjectDepartmentGrant[]>([]), departments = $state<DepartmentView[]>([]);
  let userId = $state(''), role = $state<'manager'|'member'|'viewer'>('member'), departmentId = $state(''), grantRole = $state<'member'|'viewer'>('member');
  let loading = $state(true), saving = $state(false), errorMessage = $state('');
  async function load() { loading = true; errorMessage = ''; try { const [m,g,d] = await Promise.all([listProjectMembers(projectKey), listDepartmentGrants(projectKey), listDepartments()]); members = m.data.items; grants = g.data.items; departments = d.data.items; } catch (e) { errorMessage = e instanceof Error ? e.message : '成员数据加载失败'; } finally { loading = false; } }
  onMount(load);
  async function addMember(event: SubmitEvent) { event.preventDefault(); if (!userId.trim()) return; saving=true; try { members=(await addProjectMember(projectKey,{user_id:userId.trim(),role})).data.items; userId=''; } catch(e){errorMessage=e instanceof Error?e.message:'添加成员失败'} finally{saving=false} }
  async function changeRole(member: ProjectMember, event: Event) { const value=(event.currentTarget as HTMLSelectElement).value as ProjectMember['role']; try { members=(await updateProjectMember(projectKey,member.user_id,value)).data.items; } catch(e){errorMessage=e instanceof Error?e.message:'修改角色失败'} }
  async function revoke(member: ProjectMember) { if(!(await confirmDialog({ title: '撤销成员', message: `确定撤销 ${member.display_name} 的项目成员资格吗？`, confirmLabel: '撤销', danger: true })))return; try{members=(await revokeProjectMember(projectKey,member.user_id)).data.items}catch(e){errorMessage=e instanceof Error?e.message:'撤销失败'} }
  async function addGrant(event: SubmitEvent) { event.preventDefault(); if(!departmentId)return; saving=true; try{grants=(await grantDepartment(projectKey,departmentId,grantRole)).data.items;departmentId=''}catch(e){errorMessage=e instanceof Error?e.message:'授权失败'}finally{saving=false} }
  async function revokeGrant(id:string){if(!(await confirmDialog({ title: '撤销部门授权', message: '确定撤销该部门授权吗？', confirmLabel: '撤销', danger: true })))return;try{grants=(await revokeDepartmentGrant(projectKey,id)).data.items}catch(e){errorMessage=e instanceof Error?e.message:'撤销授权失败'}}
</script>
<PageHeader title="成员与部门授权" eyebrow="Members" description="项目负责人通过显式成员表达；部门授权沿层级向下生效，其成员也会出现在左侧名单中。" />
{#if errorMessage}<div class="workspace-card error-state">{errorMessage}</div>{/if}
{#if loading}<section class="workspace-card state-box">正在加载权限配置…</section>{:else}<div class="two-column"><section class="workspace-card"><div class="section-heading"><div><h2>项目成员</h2><p>一个项目可以拥有多个负责人。</p></div><span>{members.length} 人</span></div><div class="member-list">{#each members as member}<div class="member-row"><div class="avatar">{member.display_name.slice(0,1)}</div><div class="member-info"><strong>{member.display_name}</strong><small>{member.source === 'department' ? `${member.account} · 来自部门 ${member.department_name ?? ''}` : member.account}</small></div>{#if member.source === 'department'}<span class="dept-badge" title="由部门授权带入,调整需在右侧部门授权中操作">{member.role === 'member' ? '成员' : '观察者'}</span>{:else}<select value={member.role} onchange={(event)=>changeRole(member,event)}><option value="manager">负责人</option><option value="member">成员</option><option value="viewer">观察者</option></select><button class="text-button danger-text" onclick={()=>revoke(member)}>撤销</button>{/if}</div>{:else}<p class="empty-inline">还没有成员，可添加显式成员或授权部门。</p>{/each}</div><form class="inline-form" onsubmit={addMember}><input bind:value={userId} placeholder="输入用户 UUID" aria-label="用户 UUID" /><select bind:value={role}><option value="manager">负责人</option><option value="member">成员</option><option value="viewer">观察者</option></select><button class="primary-button" disabled={saving}>添加成员</button></form></section><section class="workspace-card"><div class="section-heading"><div><h2>部门授权</h2><p>授权会沿部门层级向下生效。</p></div><span>{grants.length} 项</span></div><div class="grant-list">{#each grants as grant}<div class="grant-row"><div><strong>{departments.find((d)=>d.id===grant.department_id)?.name || grant.department_id}</strong><small>{grant.role === 'member' ? '项目成员' : '只读观察者'}</small></div><button class="text-button danger-text" onclick={()=>revokeGrant(grant.department_id)}>撤销</button></div>{:else}<p class="empty-inline">还没有部门授权。</p>{/each}</div><form class="stack-form" onsubmit={addGrant}><label>选择部门<select bind:value={departmentId}><option value="">请选择</option>{#each departments as department}<option value={department.id}>{department.name} · {department.code}</option>{/each}</select></label><label>授权角色<select bind:value={grantRole}><option value="member">成员</option><option value="viewer">观察者</option></select></label><button class="primary-button" disabled={saving}>添加部门授权</button></form></section></div>{/if}
<style>.two-column{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.section-heading{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px}.section-heading h2{margin:0 0 5px}.section-heading p,.member-info small,.grant-row small{margin:0;color:var(--color-text-muted);font-size:13px}.member-list,.grant-list{display:grid;gap:8px}.member-row,.grant-row{display:flex;align-items:center;gap:10px;padding:11px 0;border-top:1px solid var(--color-border)}.member-info,.grant-row>div{display:grid;gap:3px;min-width:0;flex:1}.avatar{display:grid;place-items:center;width:34px;height:34px;border:1px solid var(--color-border);border-radius:50%;color:var(--color-text-secondary);background:var(--color-hover);font-weight:500}.member-row select{width:110px}
.dept-badge{padding:3px 10px;border:1px solid var(--color-border);border-radius:var(--radius-sm);color:var(--color-text-muted);font-size:12px;white-space:nowrap}.inline-form{display:flex;gap:8px;margin-top:16px}.inline-form input{flex:1}.stack-form{display:grid;gap:12px;margin-top:16px}.stack-form label{display:grid;gap:6px;font-weight:500}.text-button{border:0;background:transparent;cursor:pointer;font-weight:500}.danger-text{color:var(--color-danger)}.error-state{color:var(--color-danger);margin-bottom:16px}.state-box{text-align:center;color:var(--color-text-muted)}.empty-inline{color:var(--color-text-muted)}@media(max-width:850px){.two-column{grid-template-columns:1fr}}@media(max-width:560px){.inline-form{display:grid}.member-row{flex-wrap:wrap}.member-row select{margin-left:44px}}</style>
