<script lang="ts">
  import { onMount } from 'svelte';
  import { page } from '$app/state';
  import PageHeader from '$lib/components/PageHeader.svelte';
  import { ApiClientError } from '$lib/api/client';
  import { listStatuses } from '$lib/api/projects';
  import { createSubtask, deleteTask, getSubtasks, getTask, transitionTask } from '$lib/api/tasks';
  import type { ProjectStatus, TaskView } from '$lib/api/types';

  const taskKey = $derived(String(page.params.taskKey ?? ''));
  const projectKey = $derived(taskKey.replace(/-\d+$/, ''));
  let task = $state<TaskView | null>(null); let subtasks = $state<TaskView[]>([]); let statuses = $state<ProjectStatus[]>([]); let selectedStatus = $state(''); let subtaskTitle = $state(''); let loading = $state(true); let submitting = $state(false); let deleting = $state(false); let errorMessage = $state('');
  const statusName = (id: string) => statuses.find((status) => status.id === id)?.name || id.slice(0, 8);
  const priorityName: Record<string, string> = { urgent: '紧急', high: '高', medium: '中', low: '低', none: '无' };
  async function load() { loading = true; errorMessage = ''; try { const taskResponse = await getTask(taskKey); task = taskResponse.data; const [subtaskResponse, statusResponse] = await Promise.all([getSubtasks(taskKey), listStatuses(projectKey)]); subtasks = subtaskResponse.data; statuses = statusResponse.data; selectedStatus = task.status_id; } catch (error) { errorMessage = error instanceof ApiClientError ? error.message : '任务加载失败'; } finally { loading = false; } }
  async function changeStatus() { if (!task || !selectedStatus || selectedStatus === task.status_id) return; submitting = true; try { task = (await transitionTask(task.task_key, selectedStatus)).data; } catch (error) { errorMessage = error instanceof ApiClientError ? error.message : '状态修改失败'; selectedStatus = task.status_id; } finally { submitting = false; } }
  async function addSubtask(event: SubmitEvent) { event.preventDefault(); if (!subtaskTitle.trim()) return; submitting = true; try { await createSubtask(taskKey, { title: subtaskTitle.trim(), status_id: selectedStatus || undefined }); subtaskTitle = ''; subtasks = (await getSubtasks(taskKey)).data; } catch (error) { errorMessage = error instanceof ApiClientError ? error.message : '子任务创建失败'; } finally { submitting = false; } }
  async function removeTask() { if (!task || !confirm(`确认逻辑删除任务 ${task.task_key}？`)) return; deleting = true; try { await deleteTask(task.task_key, '用户从任务详情页发起删除'); window.location.href = `/projects/${projectKey}`; } catch (error) { errorMessage = error instanceof ApiClientError ? error.message : '任务删除失败'; } finally { deleting = false; } }
  onMount(() => { void load(); });
</script>
{#if loading}<div class="workspace-card state-box">正在加载任务详情…</div>{:else if errorMessage && !task}<div class="workspace-card state-box error-state"><strong>{errorMessage}</strong><a class="primary-button" href="/projects">返回项目列表</a></div>{:else if task}<PageHeader title={task.title} eyebrow={task.task_key} description={task.description || '暂无描述。'} /><div class="detail-grid"><section class="workspace-card main-card"><div class="field-grid"><div><span class="field-label">任务状态</span><select bind:value={selectedStatus} onchange={changeStatus} disabled={submitting}>{#each statuses as status}<option value={status.id}>{status.name}</option>{/each}{#if !statuses.length}<option value={task.status_id}>{statusName(task.status_id)}</option>{/if}</select></div><div><span class="field-label">优先级</span><strong class="priority">{priorityName[task.priority]}</strong></div><div><span class="field-label">任务编号</span><strong class="mono">#{task.task_number}</strong></div><div><span class="field-label">更新时间</span><strong>{new Date(task.updated_at).toLocaleString('zh-CN')}</strong></div></div><div class="description-block"><span class="field-label">任务描述</span><p>{task.description || '暂无描述内容。'}</p></div><div class="subtask-heading"><div><h2>子任务</h2><p>子任务不能再创建子任务。</p></div><span>{subtasks.length} 项</span></div><div class="subtask-list">{#each subtasks as subtask}<a href={`/tasks/${subtask.task_key}`}><span class="task-key">{subtask.task_key}</span><strong>{subtask.title}</strong><span class="status-pill">{statusName(subtask.status_id)}</span></a>{:else}<div class="empty-inline">还没有子任务。</div>{/each}</div><form class="subtask-form" onsubmit={addSubtask}><input bind:value={subtaskTitle} placeholder="添加一个子任务" aria-label="子任务标题" /><button class="primary-button" type="submit" disabled={submitting}>{submitting ? '添加中…' : '添加子任务'}</button></form></section><aside class="workspace-card side-card"><h2>操作</h2><p>删除采用逻辑删除，动作会写入项目操作日志。</p><button class="danger-button" type="button" onclick={removeTask} disabled={deleting}>{deleting ? '删除中…' : '逻辑删除任务'}</button>{#if errorMessage}<p class="error-message">{errorMessage}</p>{/if}</aside></div>{/if}
<style>
 h2,p{margin:0}.detail-grid{display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:18px}.main-card{display:grid;gap:24px}.field-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding-bottom:20px;border-bottom:1px solid var(--color-border)}.field-grid>div{display:grid;gap:7px;min-width:0}.field-label{color:var(--color-text-muted);font-size:12px;font-weight:700}.field-grid select{min-width:0;border:1px solid var(--color-border);border-radius:9px;padding:9px;background:white}.priority{color:var(--color-warning)}.mono{font-family:var(--font-mono)}.description-block{display:grid;gap:8px}.description-block p{white-space:pre-wrap;color:var(--color-text-secondary);line-height:1.7}.subtask-heading{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.subtask-heading h2,.side-card h2{font-size:18px}.subtask-heading p,.side-card p{margin-top:5px;color:var(--color-text-muted);font-size:13px}.subtask-heading>span{color:var(--color-text-muted);font-size:13px}.subtask-list{display:grid}.subtask-list>a{display:grid;grid-template-columns:105px minmax(0,1fr) auto;align-items:center;gap:10px;padding:12px 0;border-top:1px solid var(--color-border)}.subtask-list>a:hover strong{color:var(--color-primary)}.task-key{color:var(--color-primary-strong);font-family:var(--font-mono);font-size:12px}.empty-inline{padding:12px 0;color:var(--color-text-muted);font-size:13px}.subtask-form{display:flex;gap:8px}.subtask-form input{flex:1;min-width:0;border:1px solid var(--color-border);border-radius:9px;padding:10px 11px}.subtask-form button{border:0;white-space:nowrap}.side-card{display:grid;align-content:start;gap:12px;height:max-content}.danger-button{border:0}.error-message{color:var(--color-danger);font-size:13px}.state-box{display:grid;place-items:center;gap:12px;min-height:220px}.error-state{color:var(--color-danger)}@media(max-width:900px){.detail-grid{grid-template-columns:1fr}.field-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.field-grid{grid-template-columns:1fr}.subtask-list>a{grid-template-columns:1fr;gap:5px}.subtask-form{display:grid}.subtask-form button{width:100%}}
</style>
