<script lang="ts">
 import { page } from '$app/state'; import { onMount } from 'svelte'; import PageHeader from '$lib/components/PageHeader.svelte'; import { listMilestones, createMilestone, updateMilestone, deleteMilestone } from '$lib/api/milestones'; import { confirmDialog } from '$lib/features/ui/dialog.svelte'; import type { Milestone } from '$lib/api/types';
 const projectKey=$derived(String(page.params.projectKey ?? '')); let milestones=$state<Milestone[]>([]), name=$state(''), dueDate=$state(''), loading=$state(true), saving=$state(false), errorMessage=$state('');
 onMount(load); async function load(){try{milestones=(await listMilestones(projectKey)).data.items}catch(e){errorMessage=e instanceof Error?e.message:'里程碑加载失败'}finally{loading=false}}
 async function add(event:SubmitEvent){event.preventDefault();if(!name.trim())return;saving=true;try{const item=(await createMilestone(projectKey,{name:name.trim(),due_date:dueDate||null})).data;milestones=[item,...milestones];name='';dueDate=''}catch(e){errorMessage=e instanceof Error?e.message:'创建里程碑失败'}finally{saving=false}}
 async function toggle(item:Milestone){try{const updated=(await updateMilestone(item.id,{is_reached:!item.is_reached})).data;milestones=milestones.map(i=>i.id===item.id?updated:i)}catch(e){errorMessage=e instanceof Error?e.message:'更新里程碑失败'}}
 async function remove(item:Milestone){if(!(await confirmDialog({title:'删除里程碑',message:`确定删除里程碑“${item.name}”吗？`,confirmLabel:'删除',danger:true})))return;try{await deleteMilestone(item.id);milestones=milestones.filter(i=>i.id!==item.id)}catch(e){errorMessage=e instanceof Error?e.message:'删除里程碑失败'}}
</script>
<PageHeader title="里程碑" eyebrow="Milestone" description="用阶段目标管理项目节奏，删除采用逻辑删除。" />
{#if errorMessage}<div class="workspace-card error-state">{errorMessage}</div>{/if}<section class="workspace-card create-card"><form onsubmit={add}><input bind:value={name} placeholder="里程碑名称" aria-label="里程碑名称" /><input bind:value={dueDate} type="date" aria-label="截止日期" /><button class="primary-button" disabled={saving}>{saving?'创建中…':'新增里程碑'}</button></form></section>{#if loading}<section class="workspace-card state-box">正在加载里程碑…</section>{:else}<section class="workspace-card milestone-list">{#each milestones as item}<div class:reached={item.is_reached} class="milestone-row"><button class="check-button" onclick={()=>toggle(item)} aria-label="切换完成状态">{item.is_reached?'✓':'○'}</button><div><strong>{item.name}</strong><small>{item.due_date?`截止 ${item.due_date}`:'未设置日期'} · {item.is_reached?'已完成':'进行中'}</small></div><button class="text-button danger-text" onclick={()=>remove(item)}>删除</button></div>{:else}<p class="empty-inline">还没有里程碑。</p>{/each}</section>{/if}
<style>.create-card form{display:flex;gap:10px}.create-card input:first-child{flex:1}.milestone-list{display:grid;gap:4px}.milestone-row{display:flex;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid var(--color-border)}.milestone-row:last-child{border-bottom:0}.milestone-row>div{display:grid;gap:5px;flex:1}.milestone-row small{color:var(--color-text-muted)}.check-button{width:30px;height:30px;border:1px solid var(--color-border-strong);border-radius:50%;color:var(--color-primary);background:#fff;cursor:pointer;font-weight:900}.reached strong{text-decoration:line-through;color:var(--color-text-muted)}.text-button{border:0;background:transparent;cursor:pointer;font-weight:700}.danger-text{color:var(--color-danger)}.error-state{color:var(--color-danger);margin-bottom:16px}.state-box{text-align:center;color:var(--color-text-muted)}@media(max-width:560px){.create-card form{display:grid}.create-card button{width:100%}}</style>
