use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(Users::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(Users::Id).uuid().not_null().primary_key())
                    .col(
                        ColumnDef::new(Users::Account)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Users::PasswordHash)
                            .string_len(255)
                            .not_null(),
                    )
                    .col(ColumnDef::new(Users::DisplayName).string_len(80).not_null())
                    .col(ColumnDef::new(Users::SystemRole).string_len(32).not_null())
                    .col(
                        ColumnDef::new(Users::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(Users::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Users::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Users::DeletedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Users::DeletedBy).uuid())
                    .col(ColumnDef::new(Users::DeleteReason).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Departments::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Departments::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Departments::ParentId).uuid())
                    .col(ColumnDef::new(Departments::Name).string_len(120).not_null())
                    .col(
                        ColumnDef::new(Departments::Code)
                            .string_len(64)
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Departments::SortOrder)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Departments::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Departments::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Departments::DeletedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Departments::DeletedBy).uuid())
                    .col(ColumnDef::new(Departments::DeleteReason).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(DepartmentClosure::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(DepartmentClosure::AncestorId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepartmentClosure::DescendantId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(DepartmentClosure::Depth)
                            .integer()
                            .not_null(),
                    )
                    .primary_key(
                        Index::create()
                            .col(DepartmentClosure::AncestorId)
                            .col(DepartmentClosure::DescendantId),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(UserDepartments::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(UserDepartments::UserId).uuid().not_null())
                    .col(
                        ColumnDef::new(UserDepartments::DepartmentId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(UserDepartments::JoinedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(UserDepartments::RevokedAt).timestamp_with_time_zone())
                    .primary_key(
                        Index::create()
                            .col(UserDepartments::UserId)
                            .col(UserDepartments::DepartmentId),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Projects::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(Projects::Id).uuid().not_null().primary_key())
                    .col(
                        ColumnDef::new(Projects::ProjectKey)
                            .string_len(32)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Projects::Name).string_len(160).not_null())
                    .col(ColumnDef::new(Projects::Description).text())
                    .col(ColumnDef::new(Projects::PrimaryDepartmentId).uuid())
                    .col(ColumnDef::new(Projects::ArchivedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Projects::ArchivedBy).uuid())
                    .col(
                        ColumnDef::new(Projects::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Projects::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Projects::DeletedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Projects::DeletedBy).uuid())
                    .col(ColumnDef::new(Projects::DeleteReason).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ProjectMembers::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(ProjectMembers::ProjectId).uuid().not_null())
                    .col(ColumnDef::new(ProjectMembers::UserId).uuid().not_null())
                    .col(
                        ColumnDef::new(ProjectMembers::Role)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectMembers::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ProjectMembers::RevokedAt).timestamp_with_time_zone())
                    .primary_key(
                        Index::create()
                            .col(ProjectMembers::ProjectId)
                            .col(ProjectMembers::UserId),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ProjectDepartmentGrants::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ProjectDepartmentGrants::ProjectId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectDepartmentGrants::DepartmentId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectDepartmentGrants::Role)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectDepartmentGrants::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectDepartmentGrants::RevokedAt)
                            .timestamp_with_time_zone(),
                    )
                    .primary_key(
                        Index::create()
                            .col(ProjectDepartmentGrants::ProjectId)
                            .col(ProjectDepartmentGrants::DepartmentId),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ProjectStatuses::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ProjectStatuses::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ProjectStatuses::ProjectId).uuid().not_null())
                    .col(
                        ColumnDef::new(ProjectStatuses::Name)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectStatuses::Category)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProjectStatuses::SortOrder)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(ProjectStatuses::IsDefault)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ProjectStatuses::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Milestones::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Milestones::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Milestones::ProjectId).uuid().not_null())
                    .col(ColumnDef::new(Milestones::Name).string_len(160).not_null())
                    .col(ColumnDef::new(Milestones::DueDate).date())
                    .col(
                        ColumnDef::new(Milestones::IsReached)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Milestones::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Milestones::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Milestones::DeletedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Milestones::DeletedBy).uuid())
                    .col(ColumnDef::new(Milestones::DeleteReason).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(Tasks::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(Tasks::Id).uuid().not_null().primary_key())
                    .col(
                        ColumnDef::new(Tasks::TaskKey)
                            .string_len(40)
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Tasks::ProjectId).uuid().not_null())
                    .col(ColumnDef::new(Tasks::ParentTaskId).uuid())
                    .col(ColumnDef::new(Tasks::StatusId).uuid().not_null())
                    .col(ColumnDef::new(Tasks::MilestoneId).uuid())
                    .col(ColumnDef::new(Tasks::Title).string_len(240).not_null())
                    .col(ColumnDef::new(Tasks::Description).text())
                    .col(ColumnDef::new(Tasks::Priority).string_len(32).not_null())
                    .col(ColumnDef::new(Tasks::ReporterId).uuid().not_null())
                    .col(ColumnDef::new(Tasks::AssigneeId).uuid())
                    .col(ColumnDef::new(Tasks::DueAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(Tasks::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Tasks::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Tasks::DeletedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(Tasks::DeletedBy).uuid())
                    .col(ColumnDef::new(Tasks::DeleteReason).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_tasks_project_status_updated")
                    .table(Tasks::Table)
                    .col(Tasks::ProjectId)
                    .col(Tasks::StatusId)
                    .col(Tasks::UpdatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_tasks_parent")
                    .table(Tasks::Table)
                    .col(Tasks::ParentTaskId)
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(TaskComments::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(TaskComments::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(TaskComments::TaskId).uuid().not_null())
                    .col(ColumnDef::new(TaskComments::AuthorId).uuid().not_null())
                    .col(ColumnDef::new(TaskComments::Body).text().not_null())
                    .col(
                        ColumnDef::new(TaskComments::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(TaskComments::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(TaskComments::DeletedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(TaskComments::DeletedBy).uuid())
                    .col(ColumnDef::new(TaskComments::DeleteReason).text())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(OperationLogs::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(OperationLogs::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(OperationLogs::ActorUserId).uuid().not_null())
                    .col(
                        ColumnDef::new(OperationLogs::Module)
                            .string_len(48)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(OperationLogs::Action)
                            .string_len(48)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OperationLogs::ProjectId).uuid())
                    .col(ColumnDef::new(OperationLogs::TaskId).uuid())
                    .col(
                        ColumnDef::new(OperationLogs::TargetType)
                            .string_len(64)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OperationLogs::TargetId).uuid())
                    .col(
                        ColumnDef::new(OperationLogs::Summary)
                            .string_len(320)
                            .not_null(),
                    )
                    .col(ColumnDef::new(OperationLogs::Diff).json_binary())
                    .col(ColumnDef::new(OperationLogs::Snapshot).json_binary())
                    .col(
                        ColumnDef::new(OperationLogs::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_operation_logs_project_created")
                    .table(OperationLogs::Table)
                    .col(OperationLogs::ProjectId)
                    .col(OperationLogs::CreatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_operation_logs_task_created")
                    .table(OperationLogs::Table)
                    .col(OperationLogs::TaskId)
                    .col(OperationLogs::CreatedAt)
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(JwtRefreshTokens::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(JwtRefreshTokens::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(JwtRefreshTokens::UserId).uuid().not_null())
                    .col(
                        ColumnDef::new(JwtRefreshTokens::JtiHash)
                            .string_len(128)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(JwtRefreshTokens::IssuedAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(JwtRefreshTokens::ExpiresAt)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(JwtRefreshTokens::RevokedAt).timestamp_with_time_zone())
                    .to_owned(),
            )
            .await
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(JwtRefreshTokens::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(OperationLogs::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(TaskComments::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Tasks::Table).if_exists().to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Milestones::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(ProjectStatuses::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(ProjectDepartmentGrants::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(ProjectMembers::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Projects::Table).if_exists().to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(UserDepartments::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(DepartmentClosure::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Departments::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Users::Table).if_exists().to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum Users {
    Table,
    Id,
    Account,
    PasswordHash,
    DisplayName,
    SystemRole,
    IsActive,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    DeletedBy,
    DeleteReason,
}
#[derive(DeriveIden)]
enum Departments {
    Table,
    Id,
    ParentId,
    Name,
    Code,
    SortOrder,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    DeletedBy,
    DeleteReason,
}
#[derive(DeriveIden)]
enum DepartmentClosure {
    Table,
    AncestorId,
    DescendantId,
    Depth,
}
#[derive(DeriveIden)]
enum UserDepartments {
    Table,
    UserId,
    DepartmentId,
    JoinedAt,
    RevokedAt,
}
#[derive(DeriveIden)]
enum Projects {
    Table,
    Id,
    ProjectKey,
    Name,
    Description,
    PrimaryDepartmentId,
    ArchivedAt,
    ArchivedBy,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    DeletedBy,
    DeleteReason,
}
#[derive(DeriveIden)]
enum ProjectMembers {
    Table,
    ProjectId,
    UserId,
    Role,
    CreatedAt,
    RevokedAt,
}
#[derive(DeriveIden)]
enum ProjectDepartmentGrants {
    Table,
    ProjectId,
    DepartmentId,
    Role,
    CreatedAt,
    RevokedAt,
}
#[derive(DeriveIden)]
enum ProjectStatuses {
    Table,
    Id,
    ProjectId,
    Name,
    Category,
    SortOrder,
    IsDefault,
    CreatedAt,
}
#[derive(DeriveIden)]
enum Milestones {
    Table,
    Id,
    ProjectId,
    Name,
    DueDate,
    IsReached,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    DeletedBy,
    DeleteReason,
}
#[derive(DeriveIden)]
enum Tasks {
    Table,
    Id,
    TaskKey,
    ProjectId,
    ParentTaskId,
    StatusId,
    MilestoneId,
    Title,
    Description,
    Priority,
    ReporterId,
    AssigneeId,
    DueAt,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    DeletedBy,
    DeleteReason,
}
#[derive(DeriveIden)]
enum TaskComments {
    Table,
    Id,
    TaskId,
    AuthorId,
    Body,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    DeletedBy,
    DeleteReason,
}

#[derive(DeriveIden)]
enum OperationLogs {
    Table,
    Id,
    ActorUserId,
    Module,
    Action,
    ProjectId,
    TaskId,
    TargetType,
    TargetId,
    Summary,
    Diff,
    Snapshot,
    CreatedAt,
}
#[derive(DeriveIden)]
enum JwtRefreshTokens {
    Table,
    Id,
    UserId,
    JtiHash,
    IssuedAt,
    ExpiresAt,
    RevokedAt,
}
