<script lang="ts">
 import { page } from '$app/state'; import { goto } from '$app/navigation'; import { onMount } from 'svelte'; import PageHeader from '$lib/components/PageHeader.svelte'; import { getProject, updateProject, archiveProject, restoreProject, deleteProject } from '$lib/api/projects'; import { confirmDialog } from '$lib/features/ui/dialog.svelte'; import type { ProjectView } from '$lib/api/types';
 const projectKey=$derived(String(page.params.projectKey ?? '')); let project=$state<ProjectView|null>(null), name=$state(''), description=$state(''), saving=$state(false), errorMessage=$state(''); onMount(async()=>{try{project=(await getProject(projectKey)).data;name=project.name;description=project.description||''}catch(e){errorMessage=e instanceof Error?e.message:'项目加载失败'}});
 async function save(event:SubmitEvent){event.preventDefault();saving=true;try{project=(await updateProject(projectKey,{name:name.trim(),description})).data}catch(e){errorMessage=e instanceof Error?e.message:'保存失败'}finally{saving=false}}
 async function toggleArchive(){try{project=(await (project?.archived_at?restoreProject(projectKey):archiveProject(projectKey))).data}catch(e){errorMessage=e instanceof Error?e.message:'操作失败'}}
 async function remove(){if(!(await confirmDialog({title:'逻辑删除项目',message:`确定逻辑删除项目 ${projectKey} 吗？`,confirmLabel:'删除',danger:true})))return;try{await deleteProject(projectKey,'用户在项目设置中删除');await goto('/projects')}catch(e){errorMessage=e instanceof Error?e.message:'删除项目失败'}}
</script>
<PageHeader title="项目设置" eyebrow="Settings" description="维护项目基本信息，并执行归档、恢复和逻辑删除。" />
{#if errorMessage}<div class="workspace-card error-state">{errorMessage}</div>{/if}{#if project}<section class="workspace-card"><form class="settings-form" onsubmit={save}><label>项目名称<input bind:value={name} /></label><label>项目 Key<input value={project.project_key} disabled /></label><label>描述<textarea bind:value={description} rows="5"></textarea></label><button class="primary-button" disabled={saving}>{saving?'保存中…':'保存修改'}</button></form></section><section class="workspace-card danger-zone"><h2>危险操作</h2><p>归档不会删除项目；删除是逻辑删除，相关日志仍然保留。</p><div><button class="secondary-button" onclick={toggleArchive}>{project.archived_at?'恢复项目':'归档项目'}</button><button class="danger-button" onclick={remove}>逻辑删除项目</button></div></section>{:else}<section class="workspace-card state-box">正在加载项目…</section>{/if}
<style>.settings-form{display:grid;gap:14px;max-width:680px}.settings-form label{display:grid;gap:6px;font-weight:700}.settings-form textarea{resize:vertical}.danger-zone{margin-top:18px;border-color:#f0c7cc}.danger-zone h2{margin-top:0}.danger-zone p{color:var(--color-text-muted)}.danger-zone>div{display:flex;gap:10px}.error-state{color:var(--color-danger);margin-bottom:16px}.state-box{text-align:center;color:var(--color-text-muted)}@media(max-width:560px){.danger-zone>div{display:grid}}</style>
